### ISSUE TITLE
feat: save the Open AI Api Key when entered in the interactive mode

### ISSUE THREAD

**Issue by pkarw** [callstackincubator/cali#26]
Now I must provide it every time I run the tool - and only because I am a little bit lazy and not willing to save it once in the `.env`? It's a far too harsh punishment ;)

<img width="632" alt="image" src="https://github.com/user-attachments/assets/f38e157a-9ee1-4d5f-8431-ee93536bb4a5">

let's maybe save it in the `.env` once provided @grabbou ?

**Comment by grabbou** [comment]
Yeah, good idea, I think we can save it to `.env.local` and add it to `.gitignore` automatically. Will create a follow-up prompt to confirm that, or "Fine, I will provide it later again".

**Comment by pkarw** [comment]
Thanks for a swift reply @grabbou!

**Comment by grabbou** [comment]
just run across this while installing emscripten

```

Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /Users/grabbou/Repositories/emsdk
    /Users/grabbou/Repositories/emsdk/upstream/emscripten
- This can be done for the current shell by running:
    source "/Users/grabbou/Repositories/emsdk/emsdk_env.sh"
- Configure emsdk in your shell startup scripts by running:

```
